apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: kubelearn
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/Shared/Kubernetes/mongo-data
