apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: kubelearn
  labels:
    app: kubelearnapp
    service: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    service: webapp