apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: kubelearn
  labels:
    app: kubelearnapp
spec: 
  replicas: 1
  selector:
    matchLabels:      
      service: webapi
  template:
    metadata:
      labels:
        app: kubelearnapp
        service: webapi
    spec:
      containers:
      - name: webapi
        image: two4suited/kubelearnapp-api
        ports:
          - containerPort: 80
            protocol: TCP
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
        - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
          value: "true"
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: Mongo__UserName
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: Mongo__Password
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        - name: Mongo__ServerAddress
          value: mongo:27017
        - name: Mongo__Database
          value: "testing"

