apiVersion: v1
kind: Service
metadata:
  name: webapi
  namespace: kubelearn
  labels:
    app: kubelearnapp
    service: webapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: webapi